name: lint
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  codetypo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: node -v
      - run: npx codetypo@latest "**" --dot
