name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  action-is-pristine: # make sure nothing changes in the action.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: khulnasoft/actions/public/setup-node-pnpm@main

      - run: pnpm i
      - run: git --no-pager diff --compact-summary --exit-code

  clean-build: # make sure nothing changes with a clean build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: khulnasoft/actions/public/setup-node-pnpm@main

      - run: pnpm i

      # Ensure the repository is clean after build
      - run: pnpm clean-build

      # test TypeScript build
      - run: |
          cd action-src
          pnpm build:tsc

      - run: git --no-pager diff --compact-summary --exit-code

  coverage: # run coverage and unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: khulnasoft/actions/public/setup-node-pnpm@main
      - run: pnpm i

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: GITHUB_OUTPUT="" pnpm coverage

      - name: Upload coverage Coveralls
        uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # 2.3.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./action-src/coverage/lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@1e68e06f1dbfde0e4cefc87efeba9e4643565303 # v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: "./action-src"
          files: ./coverage/lcov.info
