name: "test-action"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:

permissions:
  contents: read

env:
  FETCH_DEPTH: 1

jobs:
  test-action: # run the action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: codetypo-action
        env:
          TEST: true
      - name: Show Results
        uses: khulnasoft/actions/public/summary@main
        with:
          text: |
            outputs:
            ``````json
            ${{ toJSON(steps.codetypo-action.outputs) }}
            ``````

            Commits Ids:
            ```
            ${{ toJSON(github.event.commits.*.id  || 'undefined') }}
            ```

  test-action-with-file: # run the action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.FETCH_DEPTH }}
      - uses: ./
        id: codetypo-action
        env:
          TEST: true
        with:
          files: |
            **/*.ts
            **/*.md
      - name: Show Results
        uses: khulnasoft/actions/public/summary@main
        with:
          text: |
            outputs:
            ``````json
            ${{ toJSON(steps.codetypo-action.outputs) }}
            ``````

  test-action-no-increment: # run the action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.FETCH_DEPTH }}
      - uses: ./
        id: codetypo-action
        env:
          TEST: true
        with:
          incremental_files_only: false
          files: |
            .
      - name: Show Results
        uses: khulnasoft/actions/public/summary@main
        with:
          text: |
            outputs:
            ``````json
            ${{ toJSON(steps.codetypo-action.outputs) }}
            ``````

  test-action-no-increment-verbose: # run the action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.FETCH_DEPTH }}
      - uses: ./
        id: codetypo-action
        with:
          incremental_files_only: false
          files: |
            **
            .*/**
          verbose: true
      - name: Show Results
        uses: khulnasoft/actions/public/summary@main
        with:
          text: |
            outputs:
            ``````json
            ${{ toJSON(steps.codetypo-action.outputs) }}
            ``````

  test-action-files-with-issues: # run the action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.FETCH_DEPTH }}
      - uses: ./
        id: codetypo-action
        with:
          incremental_files_only: false
          files: |
            fixtures/**
          config: ./fixtures/codetypo.json
          strict: false
          inline: none
      - name: Show Results
        uses: khulnasoft/actions/public/summary@main
        with:
          text: |
            outputs:
            ``````json
            ${{ toJSON(steps.codetypo-action.outputs) }}
            ``````

  test-bad-config: # run the action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.FETCH_DEPTH }}
      - uses: ./
        id: codetypo-action
        continue-on-error: true
        with:
          incremental_files_only: false
          files: |
            fixtures/**
          config: ./fixtures/codetypo-missing-import.yaml
          strict: false
          inline: none
      - name: Check Failure
        if: ${{ steps.codetypo-action.outputs.errors != '1' }}
        run: exit 1
      - name: Show Results
        if: ${{ !cancelled() }}
        uses: khulnasoft/actions/public/summary@main
        with:
          text: |
            outputs:
            ``````json
            ${{ toJSON(steps.codetypo-action.outputs) }}
            ``````
            conclusion:
            ``````json
            ${{ toJSON(steps.codetypo-action.conclusion) }}
            ``````
